### ISSUE TITLE
search with just property and without value is giving 0 resource

### ISSUE THREAD

**Issue by nczirjak-acdh** [acdh-oeaw/arche-lib#6]
if i want to get all the resources for a given property then i always get 0 resources, for example:

https://arche-dev.acdh-dev.oeaw.ac.at/api/search?property[]=http://www.w3.org/2002/07/owl%23ObjectProperty&readMode=resource

**Comment by zozlak** [comment]
Actually it works, e.g. https://arche-dev.acdh-dev.oeaw.ac.at/api/search?property[]=http://purl.org/dc/elements/1.1/creator&readMore=resource just there is no triple in the system having http://www.w3.org/2002/07/owl%23ObjectProperty as a property name (this is an OWL class - if it's somewhere, it's rather on the object position and should go into `value[]` - https://arche-dev.acdh-dev.oeaw.ac.at/api/search?value[]=http://www.w3.org/2002/07/owl%23ObjectProperty&readMore=resource).
