### ISSUE TITLE
SearchTerm order/orderByLang/count issues

### ISSUE THREAD

**Issue by nczirjak-acdh** [acdh-oeaw/arche-lib#9]
**UPDATE: 24.01.2022:**

so as we agreed, please modify the order to make it work as the "normal" ordering should be :)

count problem solved, i had an outdated arche-lib version.

And this is not a typo -> $config->orderBy = array('^https://vocabs.acdh.oeaw.ac.at/schema#hasAvailableDate'); this is the DESC ordering from the documentation, which is also working.

__________
**Original ticket was:**

on hephaistos i have the following code:
`

        $config = new \acdhOeaw\arche\lib\SearchConfig();
        $config->limit = 10;
        $config->offset = 0;
        $config->orderBy = array('^https://vocabs.acdh.oeaw.ac.at/schema#hasAvailableDate');
        $config->orderByLang = 'en';
        $term1  = new \acdhOeaw\arche\lib\SearchTerm('http://www.w3.org/1999/02/22-rdf-syntax-ns#type', 'https://vocabs.acdh.oeaw.ac.at/schema#TopCollection', '=');
        $results = $this->repo->getResourcesBySearchTerms([$term1], $config);
   
        echo '<pre>';
        var_dump($config->count);
        echo '</pre>';

`

But the ordering is not working as i expected. Doesn't matter if i use the available date or the hasTitle, both are fetching random results.

Also after the query, the $config->count value is still null.

**Comment by zozlak** [comment]
I tested the code below on hephaistos (`~/share/config/examples.php` from the point of view of host or `~/config/examples.php` from inside of the container):

```php
<?php
use \zozlak\RdfConstants as RDF;
include '/home/www-data/vendor/autoload.php';
$repo = \acdhOeaw\arche\lib\Repo::factoryFromUrl('https://arche-dev.acdh-dev.oeaw.ac.at/api');
$schema = $repo->getSchema();
$config = new \acdhOeaw\arche\lib\SearchConfig();
$config->limit = 10;
$config->offset = 0;
$config->orderBy = [$schema->creationDate];
$config->orderByLang = 'en';
$term1  = new \acdhOeaw\arche\lib\SearchTerm(RDF::RDF_TYPE, $schema->classes->topCollection, '=');

$results = $repo->getResourcesBySearchTerms([$term1], $config);
echo "total resources count (page 1): $config->count\n";
$datesPage1 = [];
foreach ($results as $i) {
    $datesPage1[] = (string) $i->getGraph()->get($schema->creationDate);
}

$config->count = null;
$config->offset = 10;
$results = $repo->getResourcesBySearchTerms([$term1], $config);
echo "total resources count (page 2): $config->count\n";
$datesPage2 = [];
foreach ($results as $i) {
    $datesPage2[] = (string) $i->getGraph()->get($schema->creationDate);
}
print_r([
    'minDatePage1' => min($datesPage1),
    'maxDatePage1' => max($datesPage1),
    'minDatePage2' => min($datesPage2),
    'maxDatePage2' => max($datesPage2),
]);
print_r([
    'datesPage1' => $datesPage1,
    'datesPage2' => $datesPage2,
]);
```
 and it gave me a following output:

```
total resources count (page 1): 15
total resources count (page 2): 15
Array
(
    [minDatePage1] => 2021-05-04T11:49:20.906342
    [maxDatePage1] => 2021-07-12+02:00
    [minDatePage2] => 2021-07-28T12:29:54.151878
    [maxDatePage2] => 2021-12-14T15:50:00.122163
)
Array
(
    [datesPage1] => Array
        (
            [0] => 2021-05-04Z
            [1] => 2021-07-01+02:00
            [2] => 2021-05-13T13:22:22.482957
            [3] => 2021-07-02+02:00
            [4] => 2021-05-07T00:00:00Z
            [5] => 2021-05-04Z
            [6] => 2021-05-04T11:49:20.906342
            [7] => 2021-06-11T15:56:06.539193
            [8] => 2021-07-12+02:00
            [9] => 2021-05-04Z
        )

    [datesPage2] => Array
        (
            [0] => 2021-08-23Z
            [1] => 2021-12-14T15:50:00.122163
            [2] => 2021-11-09Z
            [3] => 2021-07-28T12:29:54.151878
            [4] => 2021-07-29T11:07:11.087930
        )

)
```

which suggests that:

* `SearchConfig::$count` is set properly.
* Ordering works fine but **there is a caveat**. Currently the arche-lib provides the ordering guarantee only between pages. It means maximum value of the `SearchConfig->orderBy` property on page `n` is lower than minimum value of this property on page `n+1` but there's no guarantee that resources read from the interator returned by the `Repo::getResourcesBy*()` methods come in the order determined by the `SearchConfig->orderBy` property  value. We can consider it a lacking feature and add it to the arche-lib.

By the way there is a typo in your code:
```php
$config->orderBy = array('^https://vocabs.acdh.oeaw.ac.at/schema#hasAvailableDate');
```
should propbably be:
$config->orderBy = array('https://vocabs.acdh.oeaw.ac.at/schema#hasAvailableDate');

**Comment by zozlak** [comment]
arche-lib 4.0.3 orders the iterator values returned by the `getResourcesBy*()` methods according to the `SearchConfig::$orderBy` property.

**Comment by nczirjak-acdh** [comment]
Additonal info:
If we orderby the date then the $config->orderByLang should be unset.

I tested the actual version and we still have one issue:

If i order the result set based on the hasTitle then the RDF sorting first the Uppercase results and then the lowercase results.

F.e.:

  0 => string 'Arthur Schnitzler Tagebuch (1879-1931)' (length=38)
  1 => string 'Arthur Schnitzler – Briefwechsel mit Autorinnen und Autoren' (length=61)
  2 => string 'Bruckner Lexikon Digital' (length=24)
  3 => string 'Das Darlehensbuch Satzbuch CD (1438-1473) - Digitale Edition der Wiener Grundbücher' (length=84)
  4 => string 'Die Große Transformation' (length=25)
  5 => string 'Die Korrespondenz Hermann Bahr – Arthur Schnitzler' (length=52)
  6 => string 'Die Korrespondenz von Leo von Thun-Hohenstein' (length=45)
  7 => string 'Die Wiener Kopisten der Werke Anton Bruckners' (length=45)
  8 => string 'Die eierlegende Wollmilchsau' (length=28)
  9 => string 'The digitized papers of Bernhard and Hieronymus Pez (Item Descriptions)' (length=71) 


in this example the  8-> Die eierlegende Wollmilchsau should be on the position 4.

**Comment by zozlak** [comment]
After giving it a thought I think it requires database-side implementation.

There are two unsolvable issues with client-side sorting:

* Assuring the same collation is used client-side and database-side.
* Assuring in case of the preferred lang miss the same "any other value" is used.

Taking it into account it seems that the only reliable sorting method is:

* remember database sorting order used for offset/limit and pass it to the client as a dedicated technical RDF property
* remember a value database used for sorting for offset/limit and pass it to the client as yet another dedicated technical RDF property

**Comment by zozlak** [comment]
[arche-lib 4.2.0](https://github.com/acdh-oeaw/arche-lib/releases/tag/4.2.0) and [arche-core 3.4.0](https://github.com/acdh-oeaw/arche-core/releases/tag/3.4.0) introduced server-side ordering which is passed to the client.

They were release on 7th February, just I forgot to update this issue.
One more thing to add is passing the value actually used for sorting to solve the problem of unknown sorting value once there was no value in `orderByLang` language.

**Comment by zozlak** [comment]
The issue with passing the value used for sorting is that `orderBy` is an array of properties so values must be returned in a way they can be matched with the `orderBy` property.

**Comment by zozlak** [comment]
Will come with arche-core 3.5 & arche-lib 4.4
